robbrit/ossu-game-project-1

- assets/regions/Region1.json
- engine/controller.py
- engine/core.py
- engine/gui/controller.py
- engine/gui/widgets.py
- engine/ingame/controller.py
- engine/model.py
- engine/scripts.py
- game/regions/region1.py
Fixes #9 .
Changes:
* Create `engine.scripts` module, moved `load_callable` into there.
* Updated Region1 to have an activateable object at the front of a house.
* Wired in ability to receive mouse clicks.
* Set up code to handle object layers in Tiled, and convert them to sprites for handling hitbox checks.
> Added ability to activate things.

- engine/core.py
- engine/game_state.py
- engine/gui/game_state.py
- engine/ingame/game_state.py
- engine/ingame/view.py
- engine/model.py
> Don't create the model until ingame starts.

- assets/world-spec.json
- engine/core.py
- engine/ingame/view.py
- engine/model.py
No ticket for this but it was needed for #19.
> Added a world spec.

- engine/scripts.py
> Added a base script.

- engine/gui/conversation.py
- engine/gui/game_state.py
- engine/gui/spec_gui.py
- engine/gui/view.py
- engine/model.py
- engine/scripts.py
- game/regions/region1.py
> Support conversations with NPCs.

- assets/gui/start-screen.json
- engine/gui/controller.py
- engine/gui/spec_gui.py
> Ported SpecGUI to arcade.gui.

- .github/workflows/pre-merge.yml
- Makefile
- engine/controller.py
- engine/core.py
- engine/game_state.py
- engine/gui/controller.py
- engine/gui/conversation.py
- engine/gui/game_state.py
- engine/gui/spec_gui.py
- engine/gui/view.py
- engine/gui/widgets.py
- engine/ingame/controller.py
- engine/ingame/game_sprite.py
- engine/ingame/game_state.py
- engine/ingame/view.py
- engine/model.py
- engine/scripts.py
- engine/spec.py
- engine/view.py
- game/gui/start.py
- pylint.toml
- requirements.txt
> Linted, made code lint compliant.

- engine/builtin.py
- engine/core.py
- engine/gui/conversation.py
- game/regions/region1.py
> Allow resuming the game.

- .github/workflows/pre-merge.yml
- Makefile
- engine/controller.py
- engine/core.py
- engine/game_state.py
- engine/gui/controller.py
- engine/gui/game_state.py
- engine/gui/spec_gui.py
- engine/gui/view.py
- engine/gui/widgets.py
- engine/ingame/controller.py
- engine/ingame/game_sprite.py
- engine/ingame/game_state.py
- engine/ingame/view.py
- engine/model.py
- engine/scripts.py
- game/gui/start.py
- game/main.py
- mypy.ini
- pylint.toml
- requirements.txt
> Wired up mypy, corrected all issues.

- engine/model.py
> `activate` hit boxes

- engine/model.py
- engine/scripts.py
> Support persisting script states across reloads.

- engine/model.py
- engine/scripts.py
> Added on_start callback.

- engine/core.py
- engine/model.py
- engine/scripts.py
- game/main.py
> Wire up player state.

- engine/core.py
- engine/ingame/game_state.py
- engine/ingame/view.py
- game/gui/hud.py
- game/main.py
> Render health bar.

- engine/core.py
- engine/model/script_zone.py
- engine/model/shapes.py
- engine/model/world.py
Refactor to pull the invisible sprite stuff out of the world class.
> Created ScriptZones class.

- assets/regions/Region2.json
- engine/model/shapes.py
> Support point-based scripted objects.

- engine/model/world.py
- engine/scripts.py
> Add `on_tick` support.

- engine/model/world.py
- engine/scripts.py
> Support passing arguments to a class-based script.

- assets/regions/Region2.json
- engine/builtin.py
- engine/model/game_sprite.py
- engine/model/script_zone.py
- engine/model/world.py
- engine/scripts.py
- game/creatures/forest.py
Refs #87.
Changes:
* Added a spawner script that will randomly spawn things at a certain rate.
* Updated script owners to have a location
* Updated `on_tick` to include a time delta.
> Added a rat spawner.

- assets/regions/Region2.json
- engine/builtin.py
- engine/model/world.py
- engine/scripts.py
- game/creatures/forest.py
> Add the ability to pass arguments to a spawned entity.

- .gitignore
- engine/core.py
- engine/scripts.py
Fixes #69 
Changes:
- Created and added signature and docstring of `get_sprites` to `GameAPI`
- And, implemented the same in `Core` class
- Also added `Scripts/` (generated by venv on windows) to .gitignore
> Added get_sprites to GameAPI

- .github/workflows/pre-merge.yml
- Makefile
- engine/model/test/test_shapes.py
- pylint.toml
> Added ability to do unit testing.

- engine/core.py
- engine/ingame/game_state.py
- engine/ingame/view.py
Fixes #126 
Added property methods for width and height. It looks like the bug that existed with self.width/height not being correct has been resolved with this refactor. As a side effect setup() doesn't do anything. I wasn't sure if there was a future use for it, so I just commented it out where it was defined and called to make sure things worked without it.
> Issue #126

- engine/core.py
- engine/model/world.py
- engine/scripts.py
Fixes #71
- Added `remove_sprite` signature to scripts.py
- Added `remove_sprite` in World class (world.py) that removes the given sprite
- Added `remove_sprite` implementation in core.py that calls world's method
> Add a remove_sprite function. Fixes #71

- engine/builtin.py
- engine/core.py
- engine/model/game_sprite.py
- engine/model/player_sprite.py
- engine/model/test/test_player_sprite.py
- engine/model/world.py
- engine/scripts.py
- game/creatures/forest.py
- game/gui/hud.py
> Added world state.

- game/main.py
As instructed, added gold. Almost added a maximum gold but thought it's better not to limit the player's wealth
> Adding money to the game

- engine/model/test/test_world.py
- engine/model/world.py
- engine/test/factories.py
> Made `create_sprite` raise on name conflict.

- engine/gui/conversation.py
> Reverse order of conversation options.

- Makefile
- engine/gui/conversation.py
- game/creatures/forest.py
- game/regions/region1.py
- game/scripts/waypoints.py
Fixes #101 .
This also makes mypy a bit stricter.
> Pulled waypoint logic into class.

- Makefile
- engine/model/physics.py
- engine/model/test/test_world.py
- engine/model/world.py
- engine/scripts.py
- game/creatures/forest.py
- game/main.py
- game/scripts/health.py
> Added enemy death.

- game/creatures/forest.py
- game/gui/hud.py
- game/main.py
- game/scripts/health.py
- pylint.toml
> Added ability for player to take damage.

- engine/core.py
- engine/event_manager.py
- engine/events.py
- engine/model/test/test_world.py
- engine/model/world.py
- engine/scripts.py
> Added custom events + sprite removed event.

- engine/builtin.py
- engine/core.py
- engine/event_manager.py
- engine/model/game_sprite.py
- engine/model/world.py
- engine/scripts.py
- pylint.toml
> Make events actually work. Spawners remove dead things.

- engine/model/game_sprite.py
- engine/model/script_zone.py
- engine/scripts.py
- game/scripts/waypoints.py
> Added facing direction.

- .gitignore
- Makefile
> Added coverage report generation.

- game/main.py
- game/quests/base.py
> Added quest data types.
